# @saas-ui-pro/* packages are private and require you to login to the private registry.
# @see https://saas-ui.dev/docs/pro/installation/yarn
npmScopes:
  saas-ui-pro:
    npmRegistryServer: 'https://npm.saas-ui.dev'
    npmAuthIdent: "sovanza-inc:941363D6-4436-4013-8615-8D48FB1D5A10"
    npmAlwaysAuth: true

# Uncomment the following if you want log in using env variables, eg for CI/CD pipelines.
# npmRegistries:
#   //npm.saas-ui.dev:
#     npmAuthIdent: '${SAAS_UI_TOKEN:-}'
#     npmAlwaysAuth: true

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "//npm.saas-ui.dev":
    npmAuthIdent: "${SAAS_UI_NPM_AUTH_IDENT}"

enableImmutableInstalls: false
